spring:
 # application:
  #  name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/microservicesUser
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update


  config:
      import: configserver:http://localhost:8085



server:
  port: 8081

#eureka:
 # instance:
 #   prefer-ip-address: true
 # client:
 #   fetch-registry: true
 #   register-with-eureka: true
 #   service-url:
 #     defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
    health:
      show-details: always

resilience4j:
  commentbreaker:
    instances:
      ratingHotelIndicatorBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slidingWindowType: COUNT_BASED
